name: Create Release on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag name
        id: get_tag
        run: echo ::set-output name=tag_name::$(git describe --tags --abbrev=0)
      
      - name: Read release note
        id: read-release-note
        run: |
          release_note=$(<release-note.md)
          echo "::set-output name=release_note::$release_note"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
          release_name: Release ${{ steps.get_tag.outputs.tag_name }}
          body: ${{ steps.read-release-note.outputs.release_note }}
          draft: false
          prerelease: false
